name: Update Index Notebook
run-name: Updating index notebook 🚀

on:
  schedule:
    - cron: '@weekly'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  convert-and-push:
    name: Convert notebook and push HTML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert

      - name: Convert notebook to HTML
        run: jupyter nbconvert index.ipynb --to html

      - name: Commit and push HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          # Check if there are changes before committing
          if ! git diff --cached --quiet; then
            git commit -m "Update index.html"
            git push
          else
            echo "No changes to commit"
          fi
